[project]
name = "nettowel"
version = "0.6.1"
description = "Network Automation Collection"
readme = "README.md"
authors = [{ name = "ubaumann", email = "github@m.ubaumann.ch" }]
license = { text = "Apache 2.0" }
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.10"
dependencies = [
    "typer>=0.16",
    "rich>=12,>=13",
    "ruamel.yaml>=0.18",
    "qrcode>=8",
    "python-dotenv>=1",
    "requests>=2",
]

[project.urls]
Homepage = "https://github.com/InfrastructureAsCode-ch/nettowel"
Documentation = "https://github.com/InfrastructureAsCode-ch/nettowel"
Repository = "https://github.com/InfrastructureAsCode-ch/nettowel"
Issues = "https://github.com/InfrastructureAsCode-ch/nettowel/issues"
Changelog = "https://github.com/InfrastructureAsCode-ch/nettowel/releases"

[project.scripts]
nettowel = "nettowel.cli.main:run"
nt = "nettowel.cli.main:run"

[project.optional-dependencies]
jinja = ["jinja2>=3", "jinja2schema>=0.1"]
ttp = ["ttp>=0.9"]
textfsm = ["textfsm>=1"]
napalm = ["napalm>=5"]
netmiko = ["netmiko>=4"]
scrapli = ["scrapli>=2025.1"]
nornir = [
    "nornir>=3.5",
    "nornir-http",
    "nornir-jinja2",
    "nornir-napalm",
    "nornir-netmiko",
    "nornir-pyxl",
    "nornir-rich",
    "nornir-scrapli",
    "nornir-utils",
]
pandas = ["pandas>=2"]
tui = ["trogon>=0.6"]
jsonpatch = ["jsonpatch>=1"]
full = [
    "jinja2",
    "jinja2schema",
    "jsonpatch",
    "napalm",
    "netmiko",
    "nornir",
    "nornir-http",
    "nornir-jinja2",
    "nornir-napalm",
    "nornir-netmiko",
    "nornir-pyxl",
    "nornir-rich",
    "nornir-scrapli",
    "nornir-utils",
    "pandas",
    "scrapli",
    "textfsm",
    "trogon",
    "ttp",
]

[build-system]
requires = ["uv_build>=0.8.4,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "black>=24.8.0",
    "mypy>=1.14.1",
    "pytest>=8.3.5",
    "types-requests>=2.32.0.20241016",
]

[tool.mypy]
python_version = "3.13"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
ignore_errors = false
ignore_missing_imports = true
strict_optional = true
warn_unused_configs = true
warn_unused_ignores = true
warn_return_any = true
warn_redundant_casts = true

[[tool.mypy.overrides]]
module = "nornir.core"
ignore_errors = true

[tool.pytest.ini_options]
markers = [
    "jinja",
    "jsonpatch",
    "ttp",
    "yaml",
]
