---
name: test nettowel
on: [push,pull_request]

jobs:
  linters:
    name: linters
    strategy:
      matrix:
        python-version: [ '3.13' ]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run black
        run: make black
      - name: Run mypy
        run: make mypy

  pytest:
    name: Testing on Python ${{ matrix.python-version }} (${{ matrix.platform}})
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
        platform: [ubuntu-latest, macos-13, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run pytest
        run: uv run pytest -vs
    
  pytest_extras:
    name: Testing ${{ matrix.extra }} on Python ${{ matrix.python-version }} (${{ matrix.platform}}) 
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]
        platform: [ubuntu-latest, macos-13, windows-latest]
        extra: [ 'jinja', 'ttp', 'jsonpatch']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --locked --extra ${{ matrix.extra }}

      - name: Run pytest
        run: uv run pytest -v -m ${{ matrix.extra }}

  release:
    name: Releasing to pypi
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [linters, pytest, pytest_extras]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.13"

      - name: prepare release
        run: make fiximageurls

      - name: build release
        run: uv build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
      
      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist/*
