---
name: test nettowel
on: [push,pull_request]

jobs:
  linters:
    name: linters
    strategy:
      matrix:
        python-version: [ '3.8' ]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        run: poetry install -E full
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run black
        run: make black
      - name: Run mypy
        run: make mypy

  pytest:
    name: Testing on Python ${{ matrix.python-version }} (${{ matrix.platform}})
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
        platform: [ubuntu-latest, macOS-10.15, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        if: ${{ matrix.platform != 'windows-latest' }}  # windows hangs if using a cached venv

      - name: Install Dependencies
        run: poetry install -E full
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run pytest
        run: make pytest
    
  pytest_extras:
    name: Testing on Python ${{ matrix.python-version }} (${{ matrix.platform}}) -- extre ${{ matrix.extra }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.8', '3.9', '3.10' ]
        platform: [ubuntu-latest, macOS-10.15, windows-latest]
        extra: [ 'jinja', 'ttp']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ matrix.python-version }}-${{ runner.os }}-${{ matrix.extra }}-${{ hashFiles('**/poetry.lock') }}
        if: ${{ matrix.platform != 'windows-latest' }}  # windows hangs if using a cached venv

      - name: Install Dependencies
        run: poetry install -E ${{ matrix.extra }}
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Run pytest
        run: poetry run pytest -v -m ${{ matrix.extra }}

  release:
    name: Releasing to pypi
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    needs: [linters, pytest, pytest_extras]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: prepare release
        run: make fiximageurls

      - name: prepare release
        run: make fiximageurls

      - name: build release
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}